---
title: "Assignment 3-GGplot"
author: "Wagner Quirós"
date: "May 18, 2017"
output: html_document
---

```{r setup, echo=FALSE, message=FALSE}
setwd("/Users/wagnerquiros/Desktop/UCSB/Courses/Spring 2017/Informatics/Assignments_ESM262/esm262/docs/wk04_ggplot")
thinshallow = read.table("data/resthin.shallow.txt", header=T)
thindeep = read.table("data/resthin.deep.txt", header=T)
clim = read.table("data/sierraclim.txt", header = T)
library(dplyr)
library(tidyr)
library(ggplot2)
library(gridExtra)
library(lubridate)
```


**Part 1 and 2. Clim Figure with Temperature and Rain**

```{r plot 1, fig.align='center'}
#Monthly average temperature from tmax and tmin
clim$avg.temp <- (clim$tmin + clim$tmax)/2

#Plot Figure 1.
Figure_1 = ggplot(clim, aes(y=avg.temp,x=year))+
  stat_summary(fun.y="mean", geom="point")+
  stat_smooth()+
  theme_bw()+
  labs(x="", y="Average Temperature (Celsius)")+
  theme(axis.text.x=element_blank())+
  theme(axis.ticks.x=element_blank())
Figure_1

#Plot 2
Figure_2 = ggplot(clim, aes(y=rain, year))+
  stat_summary(fun.y="mean", geom="point")+
  stat_smooth()+theme_bw()+
  labs(x="Year", y="Average Rain (Inches)")
Figure_2

#Get both figures together.
grid.arrange(Figure_1, Figure_2)
```

**Part 3. Thindeep figure with shared and different thinning**


```{r plot 2}
p1=ggplot(thindeep, aes(x=as.factor(wy), y=plantc, fill=as.factor(shared)))+geom_boxplot() +theme_bw()
p1 = p1+labs(x="Years since thinning", y="Biomass")
p1 = p1 +theme(axis.text= element_text(face="bold", size=12), 
               plot.margin = unit(c(15,15,15,5),"pt"), axis.title = element_text(size=12))
p1
p2= p1+facet_wrap(~as.factor(thin))
p2
```

**Part 4. Thindeep figure with shared and different thinning**
```{r plot 3}

p1=ggplot(thindeep, aes(x=scen, y=trans, col=as.factor(thin)))+theme_bw()+labs(x="", y="Transpiration") + theme(axis.text.x=element_blank())+
  theme(axis.ticks.x=element_blank()) + stat_summary(fun.y="mean", geom="line")
p1 = p1 +theme(axis.text= element_text(face="bold", size=14))


p2=ggplot(thindeep, aes(x=scen, y=evap, col=as.factor(thin)))+theme_bw()+labs(x="Year", y="Evaporation") + stat_summary(fun.y="mean", geom="line")
p2 = p2 +theme(axis.text= element_text(face="bold", size=14))
p2 + scale_color_brewer(type="div", palette="Spectral", name="Thin Intensity", labels=lnms) +
       theme(legend.position=c(0.9,0.2), legend.background=element_rect(fill="seashell2")) 
grid.arrange(p1, p2)
```























